### ISSUE TITLE
Wrong handling of stake locking transactions

### ISSUE THREAD

**Issue by saschaseewald** [loki-project/loki-android-wallet#28]
I run a Loki Masternode and have setup a view-only account to monitor the daily inflow of rewards.  

Though I can see the daily transaction in the app, I noticed the total balance differs from the balance shown in Loki Electron Wallet 1.3.3. Looking deeper into it, It turned out that the app handles transactions related to stake locking differently. 

Locking the stake has no impact on the balance in Loki Electron Wallet. But in the app the staking amount is added to the total balance, eventually resulting in a wrong balance.

**Comment by Mikunj** [comment]
Interesting, i will investigate this further

**Comment by saschaseewald** [comment]
> 
> 
> Interesting, i will investigate this further

Any news on this one?

**Comment by Mikunj** [comment]
> > Interesting, i will investigate this further
> 
> Any news on this one?

I think the difference in the balance is caused by the difference in wallet types. 

On Android you're using a view-only account which is meant to accumulate funds, it can't tell when a transaction has left the wallet so the balance should be strictly increasing. [See this Stack Exchange link for more details](https://monero.stackexchange.com/questions/7217/view-only-wallets-only-shows-incoming-transactions-only-how-to-see-outgoing-asw)

The electron wallet doesn't have a view-only wallet and by default is a full wallet so the balance remains in check.

**Comment by saschaseewald** [comment]
> 
> 
> > > Interesting, i will investigate this further
> > 
> > 
> > Any news on this one?
> 
> I think the difference in the balance is caused by the difference in wallet types.
> 
> On Android you're using a view-only account which is meant to accumulate funds, it can't tell when a transaction has left the wallet so the balance should be strictly increasing. [See this Stack Exchange link for more details](https://monero.stackexchange.com/questions/7217/view-only-wallets-only-shows-incoming-transactions-only-how-to-see-outgoing-asw)
> 
> The electron wallet doesn't have a view-only wallet and by default is a full wallet so the balance remains in check.

Thank you for the explanation.
I'll switch over to a full wallet on Android.
