### ISSUE TITLE
wallet problems

### ISSUE THREAD

**Issue by massimomining** [loki-project/loki-android-wallet#5]
hi , i download the new wallet for windows , but begin to sync and after few minutes it's like frozen , i try it also il low res mode , please help me

**Comment by blascokoa** [comment]
Same issue, it starts syncing and break after get some blocks, total balance is not updated.

**Comment by Doy-lee** [comment]
@massimomining I'm assuming you are referring to the Windows wallet and not a problem related to the Android wallet. I noticed that Windows has reflagged our executables because they are new binaries with new signatures, and are being quarantined by Windows Defender.

Ensure that lokid.exe is present in the directory where the GUI is. I also recommend running the daemon separately from the GUI so you can see what is happening when it's trying to sync.

@blascokoa Is this issue related to the Android wallet or the desktop wallet? For either applications, additional information, screenshots and or specific behaviour occurring would be helpful in figuring out what's going wrong.

**Comment by blascokoa** [comment]
@Doy-lee today my issue was on Android wallet, the issue maybe was with the node, today I try again and it works without issues.
